# Generated by Django 6.1 on 2026-09-05 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('status_change', 'تغییر وضعیت'), ('cancel', 'لغو'), ('reply', 'پاسخ')], editable=False, max_length=20)),
                ('target_type', models.CharField(editable=False, max_length=100)),
                ('target_id', models.CharField(blank=True, editable=False, max_length=64)),
                ('target_label', models.CharField(blank=True, editable=False, max_length=255)),
                ('description', models.TextField(blank=True, editable=False)),
                ('changes', models.JSONField(blank=True, default=dict, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['admin', 'created_at'], name='management__admin_i_baae8f_idx'), models.Index(fields=['action', 'created_at'], name='management__action_1dd31e_idx')],
            },
        ),
    ]
