# Generated by Django 6.1 on 2026-09-06 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orderitem_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('wallet', 'کیف پول'), ('test', 'درگاه آزمایشی')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('canceled', 'لغوشده'), ('refunded', 'بازگشت داده\u200cشده')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_must_be_positive'), models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('order',), name='one_successful_payment_per_order')],
            },
        ),
    ]
