# Generated by Django 6.1 on 2026-09-01 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید بین ۱۰ تا ۱۵ رقم باشد.', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
