# Generated by Django 6.1 on 2026-09-07 22:00

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_wallet_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=config.uploads.PrivateTicketStorage(), upload_to=config.uploads.ticket_upload_path),
        ),
    ]
