# Generated by Django 6.1 on 2026-09-06 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orderitem_unit_price'),
        ('payments', '0002_payment_refund_reference_payment_refunded_at'),
        ('shop', '0003_productdiscount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('issued', 'صادرشده'), ('refunded', 'بازگشت وجه')], default='issued', editable=False, max_length=20)),
                ('buyer_name', models.CharField(editable=False, max_length=150)),
                ('buyer_phone', models.CharField(editable=False, max_length=15)),
                ('buyer_email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('province', models.CharField(editable=False, max_length=100)),
                ('city', models.CharField(editable=False, max_length=100)),
                ('address', models.TextField(editable=False)),
                ('postal_code', models.CharField(editable=False, max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('shipping_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_gateway', models.CharField(editable=False, max_length=20)),
                ('payment_reference', models.CharField(editable=False, max_length=100)),
                ('issued_at', models.DateTimeField(editable=False)),
                ('refunded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(editable=False, max_length=200)),
                ('quantity', models.PositiveIntegerField(editable=False)),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='shop.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='invoice_shipping_cost_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='invoice_total_amount_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_item_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_item_unit_price_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='invoice_item_total_price_is_not_negative'),
        ),
    ]
