# Generated by Django 6.1 on 2026-09-05 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('orders', '0005_order_tax_amount'),
        ('payments', '0002_payment_refund_reference_payment_refunded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_tax_amount_is_not_negative'),
        ),
    ]
