# Generated by Django 6.1 on 2026-09-02 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='discount_coupons', to='shop.category')),
                ('products', models.ManyToManyField(blank=True, related_name='discount_coupons', to='shop.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='discount_coupon_amount_is_positive'), models.CheckConstraint(condition=models.Q(('discount_type', 'fixed'), models.Q(('amount__lte', 100), ('discount_type', 'percent')), _connector='OR'), name='discount_coupon_percent_is_at_most_100'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='discount_coupon_ends_after_start'), models.CheckConstraint(condition=models.Q(('max_usage__isnull', True), ('max_usage__gt', 0), _connector='OR'), name='discount_coupon_max_usage_is_positive'), models.CheckConstraint(condition=models.Q(('per_user_limit__isnull', True), ('per_user_limit__gt', 0), _connector='OR'), name='discount_coupon_per_user_limit_is_positive')],
            },
        ),
    ]
