# Generated by Django 6.1 on 2026-09-02 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_discountcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='discountcoupon',
            name='discount_coupon_amount_is_positive',
        ),
        migrations.RemoveConstraint(
            model_name='discountcoupon',
            name='discount_coupon_percent_is_at_most_100',
        ),
        migrations.RemoveConstraint(
            model_name='discountcoupon',
            name='discount_coupon_ends_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='discountcoupon',
            name='discount_coupon_max_usage_is_positive',
        ),
        migrations.RemoveConstraint(
            model_name='discountcoupon',
            name='discount_coupon_per_user_limit_is_positive',
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='shop.product'),
        ),
        migrations.RemoveField(
            model_name='discountcoupon',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='discountcoupon',
            name='products',
        ),
        migrations.AddConstraint(
            model_name='productdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('percent__gt', 0), ('percent__lte', 100)), name='product_discount_percent_between_1_and_100'),
        ),
        migrations.AddConstraint(
            model_name='productdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='product_discount_ends_after_start'),
        ),
        migrations.DeleteModel(
            name='DiscountCoupon',
        ),
    ]
