# Generated by Django 6.1 on 2026-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
