# Generated by Django 6.1 on 2026-09-05 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_wallet_wallettransaction_and_more'),
        ('orders', '0005_order_tax_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='order_tax_amount_is_not_negative'),
        ),
    ]
