# Generated by Django 6.1 on 2026-09-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_status', 'وضعیت سفارش'), ('payment_success', 'پرداخت موفق'), ('payment_failed', 'پرداخت ناموفق'), ('payment_refunded', 'بازگشت وجه'), ('invoice_issued', 'صدور فاکتور'), ('ticket_reply', 'پاسخ تیکت'), ('system', 'سیستمی')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('target_url', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('unique_key', models.CharField(blank=True, editable=False, max_length=150, null=True, unique=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
