# Generated by Django 6.1 on 2026-09-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_status', 'وضعیت سفارش'), ('payment_success', 'پرداخت موفق'), ('payment_failed', 'پرداخت ناموفق'), ('payment_refunded', 'بازگشت وجه'), ('invoice_issued', 'صدور فاکتور'), ('ticket_reply', 'پاسخ تیکت'), ('review_reply', 'پاسخ نظر'), ('system', 'سیستمی')], db_index=True, max_length=30),
        ),
    ]
